In [6]:
import joblib

In [17]:
path = 'C:/Users/Lenovo/Desktop/vscode/kdt-ai-aws/'
vectorizer = joblib.load(path+'model/ml_vectorizer.pkl')
model = joblib.load(path+'model/ml_model.pkl')

In [34]:
text = ["재미있는거 같지만 없음","나는 진짜 돈 줘도 안볼듯 ㅋㅋ"]

#임베딩
model_input = vectorizer.transform(text)
print(f'텍스트 -> {model_input.shape}')

텍스트 -> (2, 100000)


In [38]:
print(model_input.asformat('array'))

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [30]:
model_input

<2x100000 sparse matrix of type '<class 'numpy.int64'>'
	with 8 stored elements in Compressed Sparse Row format>

In [41]:
model_output = model.predict_proba(model_input)
print(model_output)
model_output = model_output.argmax(axis=1)
print(model_output)

[[0.84025185 0.15974815]
 [0.59983712 0.40016288]]
[0 0]


In [42]:
id2label = {0:'nagative',1:'positive'}

In [44]:
for a in model_output:
    print(id2label[a])

nagative
nagative


#핸들러 동작 확인

In [1]:
from model import MLModelHandler

In [2]:
ml_handler = MLModelHandler()

In [3]:
text = [
    "정말 재미있다",
    "정말 재미있는거 같지만 개똥 노잼임"
]
ml_handler.handle(text)

(['positive', 'negative'], array([0.93033628, 0.9239771 ]))

In [1]:
pip freeze > requirement.txt

Note: you may need to restart the kernel to use updated packages.
