In [6]:
import joblib

In [17]:
path = 'C:/Users/Lenovo/Desktop/vscode/kdt-ai-aws/'
vectorizer = joblib.load(path+'model/ml_vectorizer.pkl')
model = joblib.load(path+'model/ml_model.pkl')

In [34]:
text = ["재미있는거 같지만 없음","나는 진짜 돈 줘도 안볼듯 ㅋㅋ"]

#임베딩
model_input = vectorizer.transform(text)
print(f'텍스트 -> {model_input.shape}')

텍스트 -> (2, 100000)


In [38]:
print(model_input.asformat('array'))

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [30]:
model_input

<2x100000 sparse matrix of type '<class 'numpy.int64'>'
	with 8 stored elements in Compressed Sparse Row format>

In [41]:
model_output = model.predict_proba(model_input)
print(model_output)
model_output = model_output.argmax(axis=1)
print(model_output)

[[0.84025185 0.15974815]
 [0.59983712 0.40016288]]
[0 0]


In [42]:
id2label = {0:'nagative',1:'positive'}

In [44]:
for a in model_output:
    print(id2label[a])

nagative
nagative


#핸들러 동작 확인

In [1]:
from model import MLModelHandler , DLModelHandler

In [2]:
dl_handler = DLModelHandler()

c:\Users\minki\miniconda3\envs\dl_venv\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [4]:
text = [
    "정말 재미있다",
    "정말 재미있는거 같지만 개똥 노잼임"
]
dl_handler.handle(text)

(['positive', 'positive'], array([0.91821635, 0.90080076]))

In [3]:
import torch

In [5]:
from transformers.file_utils import is_torch_available

a = 1 if is_torch_available else 0
print(a)

1


#Flask test

In [8]:
!curl -d '{"text": ["영화 오랜만에 봤는데 괜찮은 영화였어","정말 지루했어"],"model_type":"ml"}' \
    -H "Content-Type: application/json" \
    -X "POST" \
    http://localhost:5000/predict


curl: (3) bad range specification in URL position 2:
[��ȭ �������� �ôµ� ������ ��ȭ����,���� �����߾�],model_type:ml}'
 ^
